### ISSUE TITLE
questions about export and wasm/webgpu

### ISSUE THREAD

**Issue by eyaler** [vladmandic/anime#1]
Thanks for your awesome work. i am trying to re-implement whitebox cartoonization for real time in browser video effects. would be grateful to get some insight on:
1. What is the difference between your port and https://github.com/PINTO0309/PINTO_model_zoo/tree/main/019_White-box-Cartoonization? Could you share your export script?
2. Why did you use webgl and not wasm? Do you think it might give better performance nowadays?

**Comment by vladmandic** [comment]
wasm will use cpu. its great, but you rarely have full gpu acceleration, not in tfjs-wasm.
webgl will use gpu if its available.
nowadays, i'd probably switch to webgpu which is more modern than webgl.

regarding differences in weights, probably near-zero if conversion and quantization was done right. i cant check now full details of pinto's conversion process, but typically his ports are pretty good.

**Comment by eyaler** [comment]
Thanks! following your advice i added a tfjs/webgpu whitebox cartoonization to my demo here: https://github.com/eyaler/LordTubeMaster

If it helps anyone - draw code looks like this:
```
    tf.tidy(() => {
        rgb = model.execute(tf.tensor4d(rgb, [1, H, W, 3])
                                             .resizeBilinear([720, 720])
                                             .div(127.5)
                                             .sub(1))
                            .squeeze()
                            .add(1)
                            .div(2)
        tf.browser.draw(rgb, canvas)
    })
    await queue.onSubmittedWorkDone()  // This reduces lag
```
It was somewhat faster then your custom GL on a discrete GPU.

**Comment by vladmandic** [comment]
> It was somewhat faster then your custom GL on a discrete GPU.

`tf.browser.draw` helper function was recently updated to use similar approach as my custom gl. before that, it was much slower.
